"""Add default values to user

Revision ID: 3005f8a0a2a6
Revises: f21fb50b826f
Create Date: 2024-01-18 00:37:30.515830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3005f8a0a2a6'
down_revision: Union[str, None] = 'f21fb50b826f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
