"""change name user_id

Revision ID: ce64c905d962
Revises: 3005f8a0a2a6
Create Date: 2024-02-04 11:06:17.645717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce64c905d962'
down_revision: Union[str, None] = '3005f8a0a2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###
