name: Deliver code to VPS

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
            host: ${{ secrets.VPS_IP }} 
            user: ${{ secrets.VPS_USER }}
            private_key: ${{ secrets.VPS_PRIVATE_KEY }} 
            command: echo 'hello world!!!!!!AAAAAAAAAA' 
