# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_run:
    workflows: [Run tests]
    types: [completed]
  workflow_dispatch:

env:
  MODE: ${{ vars.MODE }}
  LOG_LEVEL: ${{ vars.LOG_LEVEL }}

  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

  TEST_POSTGRES_DB: ${{ secrets.TEST_POSTGRES_DB }}
  TEST_POSTGRES_USER: ${{ secrets.TEST_POSTGRES_USER }}
  TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
  TEST_POSTGRES_HOST: ${{ secrets.TEST_POSTGRES_HOST }}
  TEST_POSTGRES_PORT: ${{ secrets.TEST_POSTGRES_PORT }}

  SECRET_KEY: ${{ secrets.SECRET_KEY }}

  PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}

  ADMIN_SECRET_KEY: ${{ secrets.ADMIN_SECRET_KEY }}

  ALGORITHM: ${{ secrets.ALGORITHM }}

  CORS_HEADERS: ${{ vars.CORS_HEADERS }}
  CORS_ORIGINS: ${{ vars.CORS_ORIGINS }}
  CORS_METHODS: ${{ vars.CORS_METHODS }}

  JUPYTER_PLATFORM_DIRS: ${{ vars.JUPYTER_PLATFORM_DIRS }}

  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
