name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Make the script files executable
        run: chmod +x create_env.sh

      - name: Create env file
        run: ../create_env.sh

      - name: Start container
        run: docker-compose -f "docker-compose.test.yml" up --build
      
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.test.yml" down
